#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if [[ ! ${DB_HOST:?Requires DB_HOST} \
   || ! ${DB_USERNAME:?Requires DB_USERNAME} \
   || ! ${DB_PASSWORD:?Requires DB_PASSWORD} ]]; then
  exit 1
fi

dir=$(dirname ${BASH_SOURCE[0]})
csv_dir="${dir}/../csv/"

delete_indexes="${dir}/../sql/gnindex_delete_indexes.sql"
create_indexes="${dir}/../sql/gnindex_create_indexes.sql"
db=gnindex
declare -a tables=(
                data_sources
                # name_string_indices
                # name_strings
                name_strings__author_words
                name_strings__genus
                name_strings__species
                name_strings__subspecies
                name_strings__uninomial
                name_strings__year
                vernacular_string_indices
                vernacular_strings
              );

function sql {
  PGPASSWORD=${DB_PASSWORD} psql -U ${DB_USERNAME} -h ${DB_HOST} -d ${db} -c $1 # -A -t
}

function sql_file {
  PGPASSWORD=${DB_PASSWORD} psql -U ${DB_USERNAME} -h ${DB_HOST} -d ${db} < $1 2> /dev/null
}

# Remove indexes
sql_file ${delete_indexes}

# Import data
for table in ${tables[@]}
do
  echo "Processing ${table}"
  sql "TRUNCATE TABLE ${table}"
  sql "\COPY ${table} FROM '${csv_dir}${table}.csv' WITH (FORMAT csv, HEADER)"
done

# Recreate indexes
sql_file ${create_indexes}
